version: '3'

services:
  nest_pauloslv:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'nest_pauloslv'
    restart: always
    volumes:
      - nest_pauloslv-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  nest_pauloslv-data: